#codigo despues de esta liena
global:
  scrape_interval:     30s # El intervalo en el que se traeralas metricas
  evaluation_interval: 30s # Evaluara las reglas cada 30 segundos, por defecto es cada minuto

#rule_files:
  #- "alerting_rules.yml"

scrape_configs:

  - job_name: 'Prometheus_master'
    honor_labels: true
   #metrics_path: '/federate'
    params:
      'match[]':
        - '{__name__=~".+"}'
    static_configs:


      # ------------------------------------- #
      # ============ SERVIDORES ==============#
      # ------------------------------------- #
      - targets: ['1xx.xx.1xxx.7:9100']
        labels:
          proveedor: 'AWS'
          proyecto: 'Desarrollo'
          cliente: 'QA'
          componente: 'Rutas inteligentes'
          host: '1xx.xx.1xxx.7'
      
